############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "FAQ"
url = "https://meta.wikigrid.com/wiki/FAQ"
weight = 2

[[main]]
name = "Central Wiki"
url = "https://meta.wikigrid.com"
weight = 3

[[main]]
name = "Help desk"
url = "https://meta.wikigrid.com/wiki/Help_desk"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Terms of Service"
url = "/tos"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy"
weight = 3
